# Generated by Django 4.2.7 on 2023-12-04 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
